using System.ComponentModel.DataAnnotations;

namespace FetchVideo.Models;

public class LinkItem
{
    [Key]  // 主键，通常自增
    public int Id { get; set; }

    public string Name { get; set; } = string.Empty; // 主播用户名

    public string Url { get; set; } = string.Empty; // 直播间地址
    
    public bool IsSubscribed { get; set; } = false;  // 默认不订阅

    public int Duration { get; set; } = 2;  // 默认录制2分钟
}

public class LinkItemDisplayDto
{
    public int Id { get; set; }                  // 序号（主键）

    public string Name { get; set; } = string.Empty;   // 主播用户名

    public string Url { get; set; } = string.Empty;    // 直播间地址（可选显示或隐藏）

    public bool IsSubscribed { get; set; }       // 是否订阅

    public string CurrentStatus { get; set; } = "空闲";  // 当前状态：空闲 / 录制中 等

    // 新增：仅当正在录制时才有值，前端根据这两个字段计算剩余时间
    public DateTime? StartTime { get; set; }  // 录制开始时间（UTC 或本地时间，保持一致即可）

    public int DurationSeconds { get; set; } = 0;  // 计划录制时长（秒）
}

// 请求模型（只用于单个操作）
public class SubscribeRequest
{
    public int? Id { get; set; }
}

public static class LinkItemSQL
{
    // 创建SQL时的默认列表
    public static List<LinkItem> DefaultList()
    {
        return new List<LinkItem>
        {
            // 订阅的
            new LinkItem { Name = "牛角包去睡了"      , Url = "https://live.bilibili.com/1904551806", IsSubscribed = true },
            new LinkItem { Name = "废宅三文鱼"        , Url = "https://live.bilibili.com/1871979231", IsSubscribed = true },
            new LinkItem { Name = "番外の宅"          , Url = "https://live.bilibili.com/1930407195", IsSubscribed = true },
            new LinkItem { Name = "小福包iu_"         , Url = "https://live.bilibili.com/1868870262", IsSubscribed = true },
            new LinkItem { Name = "秋日小懒"          , Url = "https://live.bilibili.com/1803295631", IsSubscribed = true },
            new LinkItem { Name = "羊莓杨莓"          , Url = "https://live.bilibili.com/1792597682", IsSubscribed = true },
            new LinkItem { Name = "枳月味奶片"        , Url = "https://live.bilibili.com/1804469695", IsSubscribed = true },
            new LinkItem { Name = "钟意大堡包"        , Url = "https://live.bilibili.com/1986467930", IsSubscribed = true },
            new LinkItem { Name = "你没下周可爱"      , Url = "https://live.bilibili.com/1872972713", IsSubscribed = true },
            new LinkItem { Name = "小四桃子"          , Url = "https://live.bilibili.com/1724212928", IsSubscribed = true },
            new LinkItem { Name = "星梨梨S"           , Url = "https://live.bilibili.com/1747118475", IsSubscribed = true },
            new LinkItem { Name = "aeri酱咩"          , Url = "https://live.bilibili.com/1948312359", IsSubscribed = true },
            new LinkItem { Name = "bili家家"          , Url = "https://live.bilibili.com/1828675450", IsSubscribed = true },
            new LinkItem { Name = "青清禾月"          , Url = "https://live.bilibili.com/1786263208", IsSubscribed = true },
            new LinkItem { Name = "秋茗ovo"           , Url = "https://live.bilibili.com/1946284495", IsSubscribed = true },
            new LinkItem { Name = "开心螺蛳粉宝宝"    , Url = "https://live.bilibili.com/1868871042", IsSubscribed = true },
            new LinkItem { Name = "香脆小海苔"        , Url = "https://live.bilibili.com/1842356567", IsSubscribed = true },
            new LinkItem { Name = "yy的小歪"          , Url = "https://live.bilibili.com/1712256876", IsSubscribed = true },
            new LinkItem { Name = "Umi今天也发财"     , Url = "https://live.bilibili.com/1840178918", IsSubscribed = true },
            new LinkItem { Name = "Aaa薯条大王_"      , Url = "https://live.bilibili.com/1787120212", IsSubscribed = true },
            new LinkItem { Name = "未薇i"             , Url = "https://live.bilibili.com/1861375125", IsSubscribed = true },
            new LinkItem { Name = "小利萝"            , Url = "https://live.bilibili.com/31734361"  , IsSubscribed = true },
            new LinkItem { Name = "濛雨清波"          , Url = "https://live.bilibili.com/21156534"  , IsSubscribed = true },
            new LinkItem { Name = "一只小梨涡a_"      , Url = "https://live.bilibili.com/1771626222", IsSubscribed = true },
            new LinkItem { Name = "草莓果酱呐"        , Url = "https://live.bilibili.com/30950163"  , IsSubscribed = true },
            new LinkItem { Name = "小鱼要饿死了"      , Url = "https://live.bilibili.com/32443468"  , IsSubscribed = true },
            new LinkItem { Name = "呀思思"            , Url = "https://live.bilibili.com/11368496"  , IsSubscribed = true },
            new LinkItem { Name = "池_渔"             , Url = "https://live.bilibili.com/1849823023", IsSubscribed = true },
            new LinkItem { Name = "小乖姿"            , Url = "https://live.bilibili.com/1849301415", IsSubscribed = true },
            new LinkItem { Name = "路人饼饼ovo"       , Url = "https://live.bilibili.com/4533196"   , IsSubscribed = true },
            new LinkItem { Name = "样样不知道"        , Url = "https://live.bilibili.com/1791356093", IsSubscribed = true },
            new LinkItem { Name = "在下小颖是也"      , Url = "https://live.bilibili.com/1904557421", IsSubscribed = true },
            new LinkItem { Name = "我是小龙虾大王"    , Url = "https://live.bilibili.com/1874223564", IsSubscribed = true },
            new LinkItem { Name = "doki小美-"         , Url = "https://live.bilibili.com/1870440922", IsSubscribed = true },
            new LinkItem { Name = "小栩小不点-"       , Url = "https://live.bilibili.com/32270626"  , IsSubscribed = true },
            new LinkItem { Name = "梗洋洋"            , Url = "https://live.bilibili.com/27880410"  , IsSubscribed = true },
            new LinkItem { Name = "牙牙大王yy-串串惯" , Url = "https://live.bilibili.com/1921278229", IsSubscribed = true },
            new LinkItem { Name = "萱萱xxOvO"         , Url = "https://live.bilibili.com/1964696515", IsSubscribed = true },
            new LinkItem { Name = "oi小汉堡"          , Url = "https://live.bilibili.com/1782085985", IsSubscribed = true },
            new LinkItem { Name = "Amelia沈梦芯"      , Url = "https://live.bilibili.com/1787122490", IsSubscribed = true },
            new LinkItem { Name = "蛋挞大王-7号生日版", Url = "https://live.bilibili.com/1942241940", IsSubscribed = true },
            new LinkItem { Name = "45透明台"          , Url = "https://live.bilibili.com/26135639"  , IsSubscribed = true },
            new LinkItem { Name = "小缘YoYo"          , Url = "https://live.bilibili.com/1948971823", IsSubscribed = true },
            new LinkItem { Name = "林一许愿提督"      , Url = "https://live.bilibili.com/1841615440", IsSubscribed = true },
            new LinkItem { Name = "_橘子_味的猫"      , Url = "https://live.bilibili.com/32058161"  , IsSubscribed = true },
            new LinkItem { Name = "苒苒不是只pig"     , Url = "https://live.bilibili.com/1012643"   , IsSubscribed = true },
            new LinkItem { Name = "-春日部_小新"      , Url = "https://live.bilibili.com/1833998881", IsSubscribed = true },
            new LinkItem { Name = "U-U悠"             , Url = "https://live.bilibili.com/1753195449", IsSubscribed = true },
            new LinkItem { Name = "漆奈奈"            , Url = "https://live.bilibili.com/1978980417", IsSubscribed = true },
            new LinkItem { Name = "kiki日記"          , Url = "https://live.bilibili.com/1712259187", IsSubscribed = true },
            new LinkItem { Name = "小梨花-hettsu冠"   , Url = "https://live.bilibili.com/1808573388", IsSubscribed = true },
            new LinkItem { Name = "美乐蒂不是坏兔子-" , Url = "https://live.bilibili.com/1737908771", IsSubscribed = true },
            new LinkItem { Name = "甜筒大王-风公子冠" , Url = "https://live.bilibili.com/1912483661", IsSubscribed = true },
            new LinkItem { Name = "来份鱼酱耶"        , Url = "https://live.bilibili.com/1814375548", IsSubscribed = true },
            new LinkItem { Name = "木木暮mu"          , Url = "https://live.bilibili.com/1917290219", IsSubscribed = true },
            new LinkItem { Name = "小兔娜娜_"         , Url = "https://live.bilibili.com/21968749"  , IsSubscribed = true },
            new LinkItem { Name = "林尤奈"            , Url = "https://live.bilibili.com/1977907120", IsSubscribed = true },
            new LinkItem { Name = "佐伊Z0E"           , Url = "https://live.bilibili.com/1732021672", IsSubscribed = true },
            new LinkItem { Name = "小芋喵_以梦冠"     , Url = "https://live.bilibili.com/1904559280", IsSubscribed = true },
            new LinkItem { Name = "小锦梨Koi"         , Url = "https://live.bilibili.com/1730463633", IsSubscribed = true },
            new LinkItem { Name = "小纱饱"            , Url = "https://live.bilibili.com/1768501487", IsSubscribed = true },
            new LinkItem { Name = "菟耳朵弯弯"        , Url = "https://live.bilibili.com/1844843241", IsSubscribed = true },
            new LinkItem { Name = "别叫我秋少-"       , Url = "https://live.bilibili.com/1901327917", IsSubscribed = true },
            new LinkItem { Name = "库洛米ちゃん"      , Url = "https://live.bilibili.com/1875097851", IsSubscribed = true },
            new LinkItem { Name = "九亿少女的梦_qwq"  , Url = "https://live.bilibili.com/1913321365", IsSubscribed = true },
            new LinkItem { Name = "允恩Sami"          , Url = "https://live.bilibili.com/1990570078", IsSubscribed = true },
            new LinkItem { Name = "-_陈念_-"          , Url = "https://live.bilibili.com/1878517257", IsSubscribed = true },
            new LinkItem { Name = "小古月yiyiyi"      , Url = "https://live.bilibili.com/1995460330", IsSubscribed = true },
            new LinkItem { Name = "スーパー无敌小猫卡", Url = "https://live.bilibili.com/1713829609", IsSubscribed = true },
            new LinkItem { Name = "樱酱又在说单口相声", Url = "https://live.bilibili.com/23122329"  , IsSubscribed = true },
            new LinkItem { Name = "李柒禾"            , Url = "https://live.bilibili.com/1878510488", IsSubscribed = true },
            new LinkItem { Name = "暴力冰桃桃15号百天", Url = "https://live.bilibili.com/1877931840", IsSubscribed = true },
            new LinkItem { Name = "百变小幸-"         , Url = "https://live.bilibili.com/1738671540", IsSubscribed = true },
            new LinkItem { Name = "瑤兔辣_"           , Url = "https://live.bilibili.com/1851658749", IsSubscribed = true },
            new LinkItem { Name = "萌萌土豆饼"        , Url = "https://live.bilibili.com/1995467486", IsSubscribed = true },
            new LinkItem { Name = "爱吃鱿鱼串串-"     , Url = "https://live.bilibili.com/1951547636", IsSubscribed = true },
            new LinkItem { Name = "u懒懒大王"         , Url = "https://live.bilibili.com/1930401879", IsSubscribed = true },
            new LinkItem { Name = "妖精七七i"         , Url = "https://live.bilibili.com/31603901"  , IsSubscribed = true },
            new LinkItem { Name = "小香菇w"           , Url = "https://live.bilibili.com/23074982"  , IsSubscribed = true },
            new LinkItem { Name = "iiiiis_is"         , Url = "https://live.bilibili.com/32668386"  , IsSubscribed = true },
            new LinkItem { Name = "oio小池抚月"       , Url = "https://live.bilibili.com/1814370257", IsSubscribed = true },
            new LinkItem { Name = "温如初超好运"      , Url = "https://live.bilibili.com/1920788307", IsSubscribed = true },
            new LinkItem { Name = "Pre芬儿"           , Url = "https://live.bilibili.com/1814403863", IsSubscribed = true },
            new LinkItem { Name = "wudi麦麦"          , Url = "https://live.bilibili.com/1879296209", IsSubscribed = true },
            new LinkItem { Name = "糖霜勾芡-"         , Url = "https://live.bilibili.com/1746701288", IsSubscribed = true },
            new LinkItem { Name = "野原一竹"          , Url = "https://live.bilibili.com/1992690884", IsSubscribed = true },
            new LinkItem { Name = "弋凌冉"            , Url = "https://live.bilibili.com/1817655234", IsSubscribed = true },
            new LinkItem { Name = "丫猫西比"          , Url = "https://live.bilibili.com/1868879735", IsSubscribed = true },
            // 不订阅的
            new LinkItem { Name = "冻泥不是冰的"      , Url = "https://live.bilibili.com/1898932569", IsSubscribed = false },
            new LinkItem { Name = "音音子ing"         , Url = "https://live.bilibili.com/1930401379", IsSubscribed = false },
            new LinkItem { Name = "kkk王可可"         , Url = "https://live.bilibili.com/1844049667", IsSubscribed = false },
            new LinkItem { Name = "草莓萱萱-"         , Url = "https://live.bilibili.com/1851391546", IsSubscribed = false },
            new LinkItem { Name = "心碎小梦丨"        , Url = "https://live.bilibili.com/31290375"  , IsSubscribed = false },
            new LinkItem { Name = "KoKo-唱见连"       , Url = "https://live.bilibili.com/1863722503", IsSubscribed = false },
            new LinkItem { Name = "鲨鱼摆摆崽"        , Url = "https://live.bilibili.com/1889475119", IsSubscribed = false },
            new LinkItem { Name = "蓓蓓Belle_"        , Url = "https://live.bilibili.com/1977901015", IsSubscribed = false },
            new LinkItem { Name = "菜崽"              , Url = "https://live.bilibili.com/563689"    , IsSubscribed = false },
            new LinkItem { Name = "w婉清w_"           , Url = "https://live.bilibili.com/21396402"  , IsSubscribed = false },
            new LinkItem { Name = "憨憨打不服"        , Url = "https://live.bilibili.com/1779344403", IsSubscribed = false },
            new LinkItem { Name = "你别芭乐我_"       , Url = "https://live.bilibili.com/1772923624", IsSubscribed = false },
            new LinkItem { Name = "你的可丽露"        , Url = "https://live.bilibili.com/1930404874", IsSubscribed = false },
            new LinkItem { Name = "QQ鱼_"             , Url = "https://live.bilibili.com/1894726568", IsSubscribed = false },
            new LinkItem { Name = "のim园子"          , Url = "https://live.bilibili.com/1974516128", IsSubscribed = false },
            new LinkItem { Name = "小蛋黄OvO"         , Url = "https://live.bilibili.com/1989949593", IsSubscribed = false },
            new LinkItem { Name = "蔓柠er"            , Url = "https://live.bilibili.com/1786565278", IsSubscribed = false },
            new LinkItem { Name = "pup111"            , Url = "https://live.bilibili.com/1850923945", IsSubscribed = false },
            new LinkItem { Name = "软水妮"            , Url = "https://live.bilibili.com/1842861593", IsSubscribed = false },
            new LinkItem { Name = "至尊强者小知恩"    , Url = "https://live.bilibili.com/1728867738", IsSubscribed = false },
            new LinkItem { Name = "空空学妹-Sub"      , Url = "https://live.bilibili.com/1725923601", IsSubscribed = false },
            new LinkItem { Name = "小蜜疯_璀璨"       , Url = "https://live.bilibili.com/1729389539", IsSubscribed = false },
            new LinkItem { Name = "甜奈-好运常伴"     , Url = "https://live.bilibili.com/1984186978", IsSubscribed = false },
            new LinkItem { Name = "周周aaaaaa-"       , Url = "https://live.bilibili.com/1871518514", IsSubscribed = false },
            new LinkItem { Name = "婉婉每天吃十个舰长", Url = "https://live.bilibili.com/1909460797", IsSubscribed = false },
            new LinkItem { Name = "影月yo-好运版"     , Url = "https://live.bilibili.com/1806667288", IsSubscribed = false },
            new LinkItem { Name = "椰椰儿o"           , Url = "https://live.bilibili.com/1732055809", IsSubscribed = false },
            new LinkItem { Name = "百变小妍-好运版"   , Url = "https://live.bilibili.com/25706804"  , IsSubscribed = false },
            new LinkItem { Name = "脆脆奶油饼干"      , Url = "https://live.bilibili.com/1920780752", IsSubscribed = false },
            new LinkItem { Name = "雪丽咪o"           , Url = "https://live.bilibili.com/1926782248", IsSubscribed = false },
            new LinkItem { Name = "语柠柠柠"          , Url = "https://live.bilibili.com/31570264"  , IsSubscribed = false },
            new LinkItem { Name = "热巧冰淇淋"        , Url = "https://live.bilibili.com/1981538843", IsSubscribed = false },
            new LinkItem { Name = "甜菜禾子"          , Url = "https://live.bilibili.com/27107598"  , IsSubscribed = false },
            new LinkItem { Name = "怼怼有点呆"        , Url = "https://live.bilibili.com/1919950136", IsSubscribed = false },
            new LinkItem { Name = "小五在呢_"         , Url = "https://live.bilibili.com/9702095"   , IsSubscribed = false },
            new LinkItem { Name = "o耶小虾"           , Url = "https://live.bilibili.com/1949983643", IsSubscribed = false },
            new LinkItem { Name = "困困小鑫OvO"       , Url = "https://live.bilibili.com/1861785276", IsSubscribed = false },
            new LinkItem { Name = "安悦Joy"           , Url = "https://live.bilibili.com/1786260439", IsSubscribed = false },
            new LinkItem { Name = "小羽ao"            , Url = "https://live.bilibili.com/1783353922", IsSubscribed = false },
            new LinkItem { Name = "迷糊在桃公主"      , Url = "https://live.bilibili.com/1746179595", IsSubscribed = false },
            new LinkItem { Name = "羊羊吃不饱-缺舰长版", Url = "https://live.bilibili.com/1977901087", IsSubscribed = false },
            new LinkItem { Name = "bili_挞挞挞挞挞挞挞", Url = "https://live.bilibili.com/1706436024", IsSubscribed = false },
            new LinkItem { Name = "泡泡oO6"           , Url = "https://live.bilibili.com/1917439599", IsSubscribed = false },
            new LinkItem { Name = "不喜欢凹"          , Url = "https://live.bilibili.com/1879294776", IsSubscribed = false },
            new LinkItem { Name = "爱冬眠的星星"      , Url = "https://live.bilibili.com/1892459932", IsSubscribed = false },
            new LinkItem { Name = "抱走柒c"           , Url = "https://live.bilibili.com/23638739"  , IsSubscribed = false },
            new LinkItem { Name = "小莞莞ovo-唱见连"  , Url = "https://live.bilibili.com/1856655856", IsSubscribed = false },
            new LinkItem { Name = "炫一口米浆"        , Url = "https://live.bilibili.com/27042745"  , IsSubscribed = false },
            new LinkItem { Name = "爱晓青呀"          , Url = "https://live.bilibili.com/32619574"  , IsSubscribed = false },
            new LinkItem { Name = "小羊没烦恼we"      , Url = "https://live.bilibili.com/1921302668", IsSubscribed = false },
            new LinkItem { Name = "肉肉Zero_"         , Url = "https://live.bilibili.com/1779353922", IsSubscribed = false },
            new LinkItem { Name = "小哔小哔呀"        , Url = "https://live.bilibili.com/1718745763", IsSubscribed = false },
            new LinkItem { Name = "徐雾阳-"           , Url = "https://live.bilibili.com/31106321"  , IsSubscribed = false },
            new LinkItem { Name = "Ameme咩咩"         , Url = "https://live.bilibili.com/23366484"  , IsSubscribed = false },
            new LinkItem { Name = "菜菜超欧气"        , Url = "https://live.bilibili.com/1707155248", IsSubscribed = false },
            new LinkItem { Name = "叫我大壮子"        , Url = "https://live.bilibili.com/25510076"  , IsSubscribed = false },
            new LinkItem { Name = "阿团睡不醒yo"      , Url = "https://live.bilibili.com/1740239241", IsSubscribed = false },
            new LinkItem { Name = "银儿-追梦版"       , Url = "https://live.bilibili.com/1920263036", IsSubscribed = false },
            new LinkItem { Name = "身体猫"            , Url = "https://live.bilibili.com/1771452742", IsSubscribed = false },
            new LinkItem { Name = "i咔咔大王"         , Url = "https://live.bilibili.com/1819585285", IsSubscribed = false },
            new LinkItem { Name = "小花粥吖"          , Url = "https://live.bilibili.com/31273118"  , IsSubscribed = false },
            new LinkItem { Name = "是柒淽嗷"          , Url = "https://live.bilibili.com/1917434400", IsSubscribed = false },
            new LinkItem { Name = "困困不摸鱼啊"      , Url = "https://live.bilibili.com/1705538400", IsSubscribed = false },
            new LinkItem { Name = "安_Joy"            , Url = "https://live.bilibili.com/1986465293", IsSubscribed = false },
            new LinkItem { Name = "熙熙兔ツ"          , Url = "https://live.bilibili.com/1991384022", IsSubscribed = false },
            new LinkItem { Name = "小鹿撞地球咯_"     , Url = "https://live.bilibili.com/1986252273", IsSubscribed = false },
            new LinkItem { Name = "咩酱好吃"          , Url = "https://live.bilibili.com/25831716"  , IsSubscribed = false },
            new LinkItem { Name = "沐川琦"            , Url = "https://live.bilibili.com/1799898897", IsSubscribed = false },
            new LinkItem { Name = "兔饱饱_酱"         , Url = "https://live.bilibili.com/1713821712", IsSubscribed = false },
            new LinkItem { Name = "圆子恰不恰"        , Url = "https://live.bilibili.com/30127882"  , IsSubscribed = false },
            new LinkItem { Name = "琳琳_yy"           , Url = "https://live.bilibili.com/1856107510", IsSubscribed = false },
            new LinkItem { Name = "小橘子yy_"         , Url = "https://live.bilibili.com/1790628531", IsSubscribed = false },
            new LinkItem { Name = "饼饼的酱"          , Url = "https://live.bilibili.com/1808576670", IsSubscribed = false },
            new LinkItem { Name = "丢丢大王TvT"       , Url = "https://live.bilibili.com/1713688500", IsSubscribed = false },
            new LinkItem { Name = "小美娜a"           , Url = "https://live.bilibili.com/1990572336", IsSubscribed = false },
            new LinkItem { Name = "小小怡-Ovo"        , Url = "https://live.bilibili.com/1985118295", IsSubscribed = false },
            new LinkItem { Name = "雪饼饱饱"          , Url = "https://live.bilibili.com/1768504934", IsSubscribed = false },
            new LinkItem { Name = "巧乐儿w"           , Url = "https://live.bilibili.com/1786269046", IsSubscribed = false },
            new LinkItem { Name = "阿鱼1月2号一周年庆典", Url = "https://live.bilibili.com/1707009633", IsSubscribed = false },
            new LinkItem { Name = "不是赔钱虎"        , Url = "https://live.bilibili.com/1962439861", IsSubscribed = false },
            new LinkItem { Name = "卷非宝宝"          , Url = "https://live.bilibili.com/1792591259", IsSubscribed = false },
            new LinkItem { Name = "好命玫瑰"          , Url = "https://live.bilibili.com/1898569298", IsSubscribed = false },
            new LinkItem { Name = "我不是小夕"        , Url = "https://live.bilibili.com/1882500991", IsSubscribed = false },
            new LinkItem { Name = "一只闪闪酱"        , Url = "https://live.bilibili.com/1828677009", IsSubscribed = false },
            new LinkItem { Name = "酥芙蕾u"           , Url = "https://live.bilibili.com/1917292772", IsSubscribed = false },
            new LinkItem { Name = "超易碎小八酱"      , Url = "https://live.bilibili.com/1874800058", IsSubscribed = false },
            new LinkItem { Name = "w晴绘晚音"         , Url = "https://live.bilibili.com/1852631602", IsSubscribed = false },
            new LinkItem { Name = "硬杮饼"            , Url = "https://live.bilibili.com/1771457267", IsSubscribed = false },
            new LinkItem { Name = "爻柒y"             , Url = "https://live.bilibili.com/1840177913", IsSubscribed = false },
            new LinkItem { Name = "梨酱猫猫w"         , Url = "https://live.bilibili.com/1816496018", IsSubscribed = false },
            new LinkItem { Name = "是只萌宠"          , Url = "https://live.bilibili.com/31735043"  , IsSubscribed = false },
            new LinkItem { Name = "芜暮com"           , Url = "https://live.bilibili.com/1990570792", IsSubscribed = false },
            new LinkItem { Name = "和_月亮私奔"       , Url = "https://live.bilibili.com/1738675595", IsSubscribed = false },
            new LinkItem { Name = "小咪定论"          , Url = "https://live.bilibili.com/1917292806", IsSubscribed = false },
            new LinkItem { Name = "高熙儿_"           , Url = "https://live.bilibili.com/1991479176", IsSubscribed = false },
            new LinkItem { Name = "Lulu气泡水"        , Url = "https://live.bilibili.com/1764694292", IsSubscribed = false },
            new LinkItem { Name = "林筱榆_唱见连"     , Url = "https://live.bilibili.com/1861377285", IsSubscribed = false },
            new LinkItem { Name = "麻酱圈圈zzz"       , Url = "https://live.bilibili.com/1780366638", IsSubscribed = false },
            new LinkItem { Name = "琪玛酥suki"        , Url = "https://live.bilibili.com/10315921"  , IsSubscribed = false },
            new LinkItem { Name = "知安知安-"         , Url = "https://live.bilibili.com/1890218578", IsSubscribed = false },
            new LinkItem { Name = "挨吃卷毛小泡面"    , Url = "https://live.bilibili.com/1840174158", IsSubscribed = false },
            new LinkItem { Name = "万迷精灵"          , Url = "https://live.bilibili.com/1792599835", IsSubscribed = false },
            new LinkItem { Name = "哪只粥"            , Url = "https://live.bilibili.com/1880711051", IsSubscribed = false },
            new LinkItem { Name = "纯情麻辣美羊羊"    , Url = "https://live.bilibili.com/1869210155", IsSubscribed = false },
            new LinkItem { Name = "止页聆"            , Url = "https://live.bilibili.com/1950855271", IsSubscribed = false },
            new LinkItem { Name = "呆玉酱_"           , Url = "https://live.bilibili.com/1782087852", IsSubscribed = false },
            new LinkItem { Name = "乖系小绵-小常冠"   , Url = "https://live.bilibili.com/1792361347", IsSubscribed = false },
            new LinkItem { Name = "封号斗罗嗯哼-体力版", Url = "https://live.bilibili.com/1920782099", IsSubscribed = false },
            new LinkItem { Name = "右碗"              , Url = "https://live.bilibili.com/1892866483", IsSubscribed = false },
            new LinkItem { Name = "佳一学姐"          , Url = "https://live.bilibili.com/1880717555", IsSubscribed = false },
            new LinkItem { Name = "猫猫雨o-0"         , Url = "https://live.bilibili.com/1782083458", IsSubscribed = false },
            new LinkItem { Name = "小芙宝_"           , Url = "https://live.bilibili.com/22060172"  , IsSubscribed = false },
            new LinkItem { Name = "kitty-可爱版"      , Url = "https://live.bilibili.com/1977907487", IsSubscribed = false },
            new LinkItem { Name = "潇靳语就是命好"    , Url = "https://live.bilibili.com/26172108"  , IsSubscribed = false },
            new LinkItem { Name = "晕晕晕了a1月10日生日", Url = "https://live.bilibili.com/1743352528", IsSubscribed = false },
            new LinkItem { Name = "AAA安安不吃香菜"   , Url = "https://live.bilibili.com/1724219519", IsSubscribed = false },
            new LinkItem { Name = "乐之之之咿"        , Url = "https://live.bilibili.com/1814403015", IsSubscribed = false },
            new LinkItem { Name = "小歪饱饱ouo-七点冠", Url = "https://live.bilibili.com/1780363967", IsSubscribed = false },
            new LinkItem { Name = "椰椰小琳-"         , Url = "https://live.bilibili.com/1784932411", IsSubscribed = false },
            new LinkItem { Name = "奶油十一prpr"      , Url = "https://live.bilibili.com/32378298"  , IsSubscribed = false },
            new LinkItem { Name = "柳下绘"            , Url = "https://live.bilibili.com/1718743370", IsSubscribed = false },
            new LinkItem { Name = "小优神u求舰长版TvT", Url = "https://live.bilibili.com/1882507490", IsSubscribed = false },
            new LinkItem { Name = "懒的猪咪"          , Url = "https://live.bilibili.com/1700894704", IsSubscribed = false },
            new LinkItem { Name = "盐汽水1_1"         , Url = "https://live.bilibili.com/1713821285", IsSubscribed = false },
            new LinkItem { Name = "小鱼比个耶"        , Url = "https://live.bilibili.com/1869214692", IsSubscribed = false },
            new LinkItem { Name = "郁兔兔-缺舰版"     , Url = "https://live.bilibili.com/1866758712", IsSubscribed = false },
            new LinkItem { Name = "草莓-疯中凌乱版"   , Url = "https://live.bilibili.com/31011120"  , IsSubscribed = false },
            new LinkItem { Name = "小z霸霸"           , Url = "https://live.bilibili.com/32265456"  , IsSubscribed = false },
            new LinkItem { Name = "粥粥一米八"        , Url = "https://live.bilibili.com/26090472"  , IsSubscribed = false },
            new LinkItem { Name = "妮妮Eva呀"         , Url = "https://live.bilibili.com/1853543807", IsSubscribed = false },
            new LinkItem { Name = "一只悠Umi"         , Url = "https://live.bilibili.com/1917439267", IsSubscribed = false },
            new LinkItem { Name = "小柿柿-好运来"     , Url = "https://live.bilibili.com/1759874816", IsSubscribed = false },
            new LinkItem { Name = "桃小满-幸运版"     , Url = "https://live.bilibili.com/1806660428", IsSubscribed = false },
            new LinkItem { Name = "玉米玖888"         , Url = "https://live.bilibili.com/1828673888", IsSubscribed = false },
            new LinkItem { Name = "卡羊西法猫"        , Url = "https://live.bilibili.com/1772921227", IsSubscribed = false },
            new LinkItem { Name = "-DOUDOU-_-"        , Url = "https://live.bilibili.com/1862086238", IsSubscribed = false },
            new LinkItem { Name = "漂亮苦瓜"          , Url = "https://live.bilibili.com/1741666266", IsSubscribed = false },
            new LinkItem { Name = "乐乐乖乖ovo"       , Url = "https://live.bilibili.com/32668732"  , IsSubscribed = false },
            new LinkItem { Name = "喵喵超级困"        , Url = "https://live.bilibili.com/1716072806", IsSubscribed = false },
            new LinkItem { Name = "可乐烧脑-"         , Url = "https://live.bilibili.com/24756620"  , IsSubscribed = false },
            new LinkItem { Name = "甜野猫-ovo"        , Url = "https://live.bilibili.com/1929633661", IsSubscribed = false },
            new LinkItem { Name = "_sweet甜茶"        , Url = "https://live.bilibili.com/1954826417", IsSubscribed = false },
            new LinkItem { Name = "猫生夏-"           , Url = "https://live.bilibili.com/12204028"  , IsSubscribed = false },
            new LinkItem { Name = "笨蛋零一"          , Url = "https://live.bilibili.com/1724213842", IsSubscribed = false },
            new LinkItem { Name = "大大-久"           , Url = "https://live.bilibili.com/1847878669", IsSubscribed = false },
            new LinkItem { Name = "小猫神三周年快乐"  , Url = "https://live.bilibili.com/26649682"  , IsSubscribed = false },
            new LinkItem { Name = "cc西西法in"        , Url = "https://live.bilibili.com/1753190812", IsSubscribed = false },
            new LinkItem { Name = "小蜜淑-抗揍版"     , Url = "https://live.bilibili.com/1747794824", IsSubscribed = false },
            new LinkItem { Name = "锦鲤梦梦_"         , Url = "https://live.bilibili.com/1713823468", IsSubscribed = false },
            new LinkItem { Name = "岁穗QuQ"           , Url = "https://live.bilibili.com/1772929973", IsSubscribed = false },
            new LinkItem { Name = "小麦兜兜W"         , Url = "https://live.bilibili.com/1841880119", IsSubscribed = false },
            new LinkItem { Name = "小魚orz"           , Url = "https://live.bilibili.com/4416247"   , IsSubscribed = false },
            new LinkItem { Name = "乔洛洛历险记"      , Url = "https://live.bilibili.com/1980662922", IsSubscribed = false },
            new LinkItem { Name = "Dd宝妈"            , Url = "https://live.bilibili.com/1716538929", IsSubscribed = false },
            new LinkItem { Name = "甜菜小爱-"         , Url = "https://live.bilibili.com/1746701302", IsSubscribed = false },
            new LinkItem { Name = "阿翡ぃ"            , Url = "https://live.bilibili.com/1999926623", IsSubscribed = false },
            new LinkItem { Name = "幸运小白ovo"       , Url = "https://live.bilibili.com/1716079489", IsSubscribed = false },
            new LinkItem { Name = "猪猪条大王"        , Url = "https://live.bilibili.com/1985020186", IsSubscribed = false },
            new LinkItem { Name = "小喵喵咪咪酱"      , Url = "https://live.bilibili.com/1829180166", IsSubscribed = false },
            new LinkItem { Name = "一只小鱼ou"        , Url = "https://live.bilibili.com/1968488810", IsSubscribed = false },
            new LinkItem { Name = "一颗熊子"          , Url = "https://live.bilibili.com/30646111"  , IsSubscribed = false },
            new LinkItem { Name = "兔叽妹妹_i"        , Url = "https://live.bilibili.com/1713827022", IsSubscribed = false },
            new LinkItem { Name = "喻可播到八十岁"    , Url = "https://live.bilibili.com/1916507098", IsSubscribed = false },
            new LinkItem { Name = "挞挞没有皮"        , Url = "https://live.bilibili.com/31414901"  , IsSubscribed = false },
            new LinkItem { Name = "雅雅-好运版"       , Url = "https://live.bilibili.com/1852354173", IsSubscribed = false },
            new LinkItem { Name = "绵绵薯饼_"         , Url = "https://live.bilibili.com/1732054486", IsSubscribed = false },
            new LinkItem { Name = "汤胆胆"            , Url = "https://live.bilibili.com/22932382"  , IsSubscribed = false },
            new LinkItem { Name = "板栗_123"          , Url = "https://live.bilibili.com/1954465030", IsSubscribed = false },
            new LinkItem { Name = "小念吖y"           , Url = "https://live.bilibili.com/1880052768", IsSubscribed = false },
            new LinkItem { Name = "野原一子"          , Url = "https://live.bilibili.com/1777480961", IsSubscribed = false },
            new LinkItem { Name = "奶酥爱吃鱼c"       , Url = "https://live.bilibili.com/1922179083", IsSubscribed = false },
            new LinkItem { Name = "小七脆脆角"        , Url = "https://live.bilibili.com/30827279"  , IsSubscribed = false },
            new LinkItem { Name = "小O的心动日记"     , Url = "https://live.bilibili.com/1996444579", IsSubscribed = false },
            new LinkItem { Name = "沈佳壹-"           , Url = "https://live.bilibili.com/1991386767", IsSubscribed = false },
            new LinkItem { Name = "Xh-川渝甜妹"       , Url = "https://live.bilibili.com/32307212"  , IsSubscribed = false },
            new LinkItem { Name = "酥歪ai"            , Url = "https://live.bilibili.com/1713543882", IsSubscribed = false },
            new LinkItem { Name = "蛋黄派掌门人a"     , Url = "https://live.bilibili.com/24629687"  , IsSubscribed = false },
            new LinkItem { Name = "开心小芋-努力版"   , Url = "https://live.bilibili.com/1779354983", IsSubscribed = false },
            new LinkItem { Name = "金安安对2026好亿点", Url = "https://live.bilibili.com/32005937"  , IsSubscribed = false },
            new LinkItem { Name = "小桥知世的黑眼圈"  , Url = "https://live.bilibili.com/1852876108", IsSubscribed = false },
            new LinkItem { Name = "冰糖雪狸_勤奋版"   , Url = "https://live.bilibili.com/1702261805", IsSubscribed = false },
            new LinkItem { Name = "宋宋喵喵来了"      , Url = "https://live.bilibili.com/1741666071", IsSubscribed = false },
            new LinkItem { Name = "小桃幸子"          , Url = "https://live.bilibili.com/1856569066", IsSubscribed = false },
            new LinkItem { Name = "御猫精灵-天天冠"   , Url = "https://live.bilibili.com/1710483999", IsSubscribed = false },
            new LinkItem { Name = "发霉的花生米"      , Url = "https://live.bilibili.com/1768089524", IsSubscribed = false },
            new LinkItem { Name = "he小泡芙"          , Url = "https://live.bilibili.com/1777488090", IsSubscribed = false },
            new LinkItem { Name = "土豆堡-体力版"     , Url = "https://live.bilibili.com/1777643588", IsSubscribed = false },
            new LinkItem { Name = "肉肉不当小哭包"    , Url = "https://live.bilibili.com/30843140"  , IsSubscribed = false },
            new LinkItem { Name = "半勺小奶酪-180"    , Url = "https://live.bilibili.com/1760810539", IsSubscribed = false },
            new LinkItem { Name = "嗳眠星星"          , Url = "https://live.bilibili.com/1892459932/", IsSubscribed = false },
            new LinkItem { Name = "桃桃不夭"          , Url = "https://live.bilibili.com/1874228937", IsSubscribed = false },
            new LinkItem { Name = "小小溜-"           , Url = "https://live.bilibili.com/1790623172", IsSubscribed = false },
            new LinkItem { Name = "小猫脸蛋"          , Url = "https://live.bilibili.com/11055730"  , IsSubscribed = false },
            new LinkItem { Name = "-抱冰冰"           , Url = "https://live.bilibili.com/1741669394", IsSubscribed = false },
            new LinkItem { Name = "笨蛋小猪_"         , Url = "https://live.bilibili.com/30194631"  , IsSubscribed = false },
            new LinkItem { Name = "星星-不打烊-_-"    , Url = "https://live.bilibili.com/32440257"  , IsSubscribed = false },
            new LinkItem { Name = "么凹猫大人"        , Url = "https://live.bilibili.com/32075349"  , IsSubscribed = false },
            new LinkItem { Name = "林眠i"             , Url = "https://live.bilibili.com/1731715967", IsSubscribed = false },
            new LinkItem { Name = "幼幼学姐-"         , Url = "https://live.bilibili.com/1861306505", IsSubscribed = false },
            new LinkItem { Name = "坏蛋小糕_"         , Url = "https://live.bilibili.com/30194646"  , IsSubscribed = false },
            new LinkItem { Name = "绵绵冰小羊羔-好运版", Url = "https://live.bilibili.com/1814192853", IsSubscribed = false },
            new LinkItem { Name = "幸运兔崽"          , Url = "https://live.bilibili.com/1935935173", IsSubscribed = false },
            new LinkItem { Name = "颜颜爱发呆"        , Url = "https://live.bilibili.com/1986468193", IsSubscribed = false },
            new LinkItem { Name = "薇子oi"            , Url = "https://live.bilibili.com/1890213937", IsSubscribed = false },
            new LinkItem { Name = "米宝宝小困包"      , Url = "https://live.bilibili.com/1842748618", IsSubscribed = false },
            new LinkItem { Name = "暴走熊公主ya"      , Url = "https://live.bilibili.com/1872979520", IsSubscribed = false },
            new LinkItem { Name = "小树-v-"           , Url = "https://live.bilibili.com/1814401173", IsSubscribed = false },
            new LinkItem { Name = "糕冷小D"           , Url = "https://live.bilibili.com/1942242175", IsSubscribed = false },
            new LinkItem { Name = "小熊不吃苦"        , Url = "https://live.bilibili.com/1881123512", IsSubscribed = false },
            new LinkItem { Name = "柚子不当小哭包"    , Url = "https://live.bilibili.com/31316745"  , IsSubscribed = false },
            new LinkItem { Name = "圆溜溜小圆_"       , Url = "https://live.bilibili.com/30733473"  , IsSubscribed = false },
            new LinkItem { Name = "特伦苏苏ss"        , Url = "https://live.bilibili.com/24612756"  , IsSubscribed = false },
            new LinkItem { Name = "温鲤L"             , Url = "https://live.bilibili.com/1783354087", IsSubscribed = false },
            new LinkItem { Name = "不礼Sama"          , Url = "https://live.bilibili.com/1787127814", IsSubscribed = false },
            new LinkItem { Name = "易嘉爱yja"         , Url = "https://live.bilibili.com/2058485"   , IsSubscribed = false },
            new LinkItem { Name = "七追追太想进步了"  , Url = "https://live.bilibili.com/32755971"  , IsSubscribed = false },
            new LinkItem { Name = "是听听鸭_"         , Url = "https://live.bilibili.com/31158724"  , IsSubscribed = false },
            new LinkItem { Name = "小七iy"            , Url = "https://live.bilibili.com/30795605"  , IsSubscribed = false },
            new LinkItem { Name = "贝贝宝-好骗版"     , Url = "https://live.bilibili.com/1991470874", IsSubscribed = false },
            new LinkItem { Name = "兔子林ouo"         , Url = "https://live.bilibili.com/24114570"  , IsSubscribed = false },
            new LinkItem { Name = "-鹿鹿不是鹿"       , Url = "https://live.bilibili.com/1955437490", IsSubscribed = false },
            new LinkItem { Name = "冉沁鹭"            , Url = "https://live.bilibili.com/1884450872", IsSubscribed = false },
            new LinkItem { Name = "小可学妹_"         , Url = "https://live.bilibili.com/1900560536", IsSubscribed = false },
            new LinkItem { Name = "栗子猫尼"          , Url = "https://live.bilibili.com/1843662726", IsSubscribed = false },
            new LinkItem { Name = "幸运的祺子"        , Url = "https://live.bilibili.com/1775715508", IsSubscribed = false },
            new LinkItem { Name = "榴芒雪雪"          , Url = "https://live.bilibili.com/27774501"  , IsSubscribed = false },
            new LinkItem { Name = "bui可可"           , Url = "https://live.bilibili.com/1889470801", IsSubscribed = false },
            new LinkItem { Name = "宅妹小菜ye-松松冠" , Url = "https://live.bilibili.com/1982184046", IsSubscribed = false },
            new LinkItem { Name = "h涵涵女王"         , Url = "https://live.bilibili.com/1917439168", IsSubscribed = false },
            new LinkItem { Name = "呆呆小妧"          , Url = "https://live.bilibili.com/1777646418", IsSubscribed = false },
            new LinkItem { Name = "wuhan安酱"         , Url = "https://live.bilibili.com/1837224396", IsSubscribed = false },
            new LinkItem { Name = "糖唐很甜-"         , Url = "https://live.bilibili.com/1812801653", IsSubscribed = false },
            new LinkItem { Name = "欢欢酱oi"          , Url = "https://live.bilibili.com/1978983714", IsSubscribed = false },
            new LinkItem { Name = "是颜羊羊呢"        , Url = "https://live.bilibili.com/22982491"  , IsSubscribed = false },
            new LinkItem { Name = "芋妳桃桃"          , Url = "https://live.bilibili.com/1912785799", IsSubscribed = false },
            new LinkItem { Name = "清纯小元u"         , Url = "https://live.bilibili.com/1775713988", IsSubscribed = false },
            new LinkItem { Name = "小小忄怡"          , Url = "https://live.bilibili.com/1718740328", IsSubscribed = false },
            new LinkItem { Name = "喵大力-耐播版"     , Url = "https://live.bilibili.com/1991477860", IsSubscribed = false },
            new LinkItem { Name = "亲亲T-T"           , Url = "https://live.bilibili.com/1908905050", IsSubscribed = false },
            new LinkItem { Name = "兔宅QAQ"           , Url = "https://live.bilibili.com/1950857249", IsSubscribed = false },
            new LinkItem { Name = "夏夏子以梦"        , Url = "https://live.bilibili.com/1862085075", IsSubscribed = false },
            new LinkItem { Name = "狐坨驾到"          , Url = "https://live.bilibili.com/25764875"  , IsSubscribed = false },
            new LinkItem { Name = "沈佳霖"            , Url = "https://live.bilibili.com/32579673"  , IsSubscribed = false },
            new LinkItem { Name = "盐汁尤梨yuri"      , Url = "https://live.bilibili.com/26311087"  , IsSubscribed = false },
            new LinkItem { Name = "树里酱Juri"        , Url = "https://live.bilibili.com/3064286"   , IsSubscribed = false },
            new LinkItem { Name = "拜见小怡大王z"     , Url = "https://live.bilibili.com/1913416006", IsSubscribed = false },
            new LinkItem { Name = "起床了小鑫-"       , Url = "https://live.bilibili.com/1738676293", IsSubscribed = false },
            new LinkItem { Name = "Hiwink"            , Url = "https://live.bilibili.com/1980661629", IsSubscribed = false },
            new LinkItem { Name = "帅气的香菜y"       , Url = "https://live.bilibili.com/32212377"  , IsSubscribed = false },
            new LinkItem { Name = "皮漾漾"            , Url = "https://live.bilibili.com/1917292736", IsSubscribed = false },
            new LinkItem { Name = "流白酱m"           , Url = "https://live.bilibili.com/1817613432", IsSubscribed = false },
            new LinkItem { Name = "小柚yuyu"          , Url = "https://live.bilibili.com/5360662"   , IsSubscribed = false },
            new LinkItem { Name = "呆呆小狼_S"        , Url = "https://live.bilibili.com/1868175749", IsSubscribed = false },
            new LinkItem { Name = "花栗鼠大队长"      , Url = "https://live.bilibili.com/27579539"  , IsSubscribed = false },
            new LinkItem { Name = "爱吃香菜_blibli"   , Url = "https://live.bilibili.com/22165719"  , IsSubscribed = false },
            new LinkItem { Name = "果粒橙1月10号生日版", Url = "https://live.bilibili.com/32224925"  , IsSubscribed = false },
            new LinkItem { Name = "陆识衣和王严言"    , Url = "https://live.bilibili.com/24561443"  , IsSubscribed = false },
            new LinkItem { Name = "穗饱饱-8号百天"    , Url = "https://live.bilibili.com/1809239271", IsSubscribed = false },
            new LinkItem { Name = "奶芙气泡U"         , Url = "https://live.bilibili.com/1869217180", IsSubscribed = false },
            new LinkItem { Name = "荔只ovo"           , Url = "https://live.bilibili.com/1716538259", IsSubscribed = false },
            new LinkItem { Name = "沐小悠喵喵"        , Url = "https://live.bilibili.com/1954350225", IsSubscribed = false },
            new LinkItem { Name = "筱玔奈奈子"        , Url = "https://live.bilibili.com/1738679236", IsSubscribed = false },
            new LinkItem { Name = "小虫日记ovo"       , Url = "https://live.bilibili.com/1828187801", IsSubscribed = false },
            new LinkItem { Name = "蛋挞-西西的主人"   , Url = "https://live.bilibili.com/1954824451", IsSubscribed = false },
            new LinkItem { Name = "十日容"            , Url = "https://live.bilibili.com/1949982472", IsSubscribed = false },
            new LinkItem { Name = "小熊软软-许愿提督" , Url = "https://live.bilibili.com/1772927173", IsSubscribed = false },
            new LinkItem { Name = "小luooooooo"       , Url = "https://live.bilibili.com/25374971"  , IsSubscribed = false },
            new LinkItem { Name = "66呆毛"            , Url = "https://live.bilibili.com/1793685059", IsSubscribed = false },
            new LinkItem { Name = "兔酱Yumi"          , Url = "https://live.bilibili.com/1921300245", IsSubscribed = false },
            new LinkItem { Name = "一只眠羊-vo"       , Url = "https://live.bilibili.com/1837225151", IsSubscribed = false },
            new LinkItem { Name = "猫九cream-33冠"    , Url = "https://live.bilibili.com/1963694926", IsSubscribed = false },
            new LinkItem { Name = "XR坂坂"            , Url = "https://live.bilibili.com/1908327456", IsSubscribed = false },
            new LinkItem { Name = "大南瓜瓜瓜瓜瓜"    , Url = "https://live.bilibili.com/1913428729", IsSubscribed = false },
            new LinkItem { Name = "姜沅沅_缺舰版"     , Url = "https://live.bilibili.com/1829180665", IsSubscribed = false },
            new LinkItem { Name = "大碗吃梨"          , Url = "https://live.bilibili.com/1886442562", IsSubscribed = false },
            new LinkItem { Name = "芝麻馅儿汤园"      , Url = "https://live.bilibili.com/12035711"  , IsSubscribed = false },
            new LinkItem { Name = "甜心纯儿-"         , Url = "https://live.bilibili.com/30902572"  , IsSubscribed = false },
            new LinkItem { Name = "Q熊Q熊Q"           , Url = "https://live.bilibili.com/1769475507", IsSubscribed = false },
            new LinkItem { Name = "无敌小菲喵OvO"     , Url = "https://live.bilibili.com/1746141883", IsSubscribed = false },
            new LinkItem { Name = "英俊的芋头"        , Url = "https://live.bilibili.com/27210962"  , IsSubscribed = false },
            new LinkItem { Name = "宅小栗ouo"         , Url = "https://live.bilibili.com/1881089062", IsSubscribed = false },
            new LinkItem { Name = "王木木爱哭--许新元冠", Url = "https://live.bilibili.com/1861788036", IsSubscribed = false },
            new LinkItem { Name = "小欲喵"            , Url = "https://live.bilibili.com/1963476346", IsSubscribed = false },
            new LinkItem { Name = "焰宝suki"          , Url = "https://live.bilibili.com/1750979036", IsSubscribed = false },
            new LinkItem { Name = "灌注大白菜"        , Url = "https://live.bilibili.com/32232237"  , IsSubscribed = false },
            new LinkItem { Name = "小鱼仔ouo-"        , Url = "https://live.bilibili.com/25111554"  , IsSubscribed = false },
            new LinkItem { Name = "慕儿YA"            , Url = "https://live.bilibili.com/22828499"  , IsSubscribed = false },
            new LinkItem { Name = "一只羊o1"          , Url = "https://live.bilibili.com/31586741"  , IsSubscribed = false },
            new LinkItem { Name = "鱼卷椰椰"          , Url = "https://live.bilibili.com/1995467149", IsSubscribed = false },
            new LinkItem { Name = "甜菜小眠o"         , Url = "https://live.bilibili.com/1950851443", IsSubscribed = false },
            new LinkItem { Name = "然然然ovo_"        , Url = "https://live.bilibili.com/1963470752", IsSubscribed = false },
            new LinkItem { Name = "巧克妮包"          , Url = "https://live.bilibili.com/1967211211", IsSubscribed = false },
            new LinkItem { Name = "小羊羊羊肖恩_"     , Url = "https://live.bilibili.com/1814404348", IsSubscribed = false },
            new LinkItem { Name = "土豆大王耶_"       , Url = "https://live.bilibili.com/1917298505", IsSubscribed = false },
            new LinkItem { Name = "泡芙妺妺-"         , Url = "https://live.bilibili.com/1776265091", IsSubscribed = false },
            new LinkItem { Name = "芝朵_"             , Url = "https://live.bilibili.com/23767966"  , IsSubscribed = false },
            new LinkItem { Name = "岁岁Umi"           , Url = "https://live.bilibili.com/1817610517", IsSubscribed = false },
            new LinkItem { Name = "柒柒爱早起"        , Url = "https://live.bilibili.com/32270726"  , IsSubscribed = false },
            new LinkItem { Name = "知知酱suki"        , Url = "https://live.bilibili.com/1791985069", IsSubscribed = false },
            new LinkItem { Name = "闪闪惹人爱TuT"     , Url = "https://live.bilibili.com/1829746319", IsSubscribed = false },
            new LinkItem { Name = "木子-Muziii"       , Url = "https://live.bilibili.com/32048607"  , IsSubscribed = false },
            new LinkItem { Name = "萌星语"            , Url = "https://live.bilibili.com/32037494"  , IsSubscribed = false },
            new LinkItem { Name = "Keylin梦"          , Url = "https://live.bilibili.com/1792594325", IsSubscribed = false },
            new LinkItem { Name = "淡淡Blessed"       , Url = "https://live.bilibili.com/1916503496", IsSubscribed = false },
            new LinkItem { Name = "渡渡鸟渡渡"        , Url = "https://live.bilibili.com/545498"    , IsSubscribed = false },
            new LinkItem { Name = "茉晴很白"          , Url = "https://live.bilibili.com/1930403235", IsSubscribed = false },
            new LinkItem { Name = "叽里咕噜在在"      , Url = "https://live.bilibili.com/1908325708", IsSubscribed = false },
            new LinkItem { Name = "星星star111"       , Url = "https://live.bilibili.com/1997905829", IsSubscribed = false },
            new LinkItem { Name = "iii--七月"         , Url = "https://live.bilibili.com/1746172471", IsSubscribed = false },
            new LinkItem { Name = "落跑甜心021"       , Url = "https://live.bilibili.com/1879295639", IsSubscribed = false },
            new LinkItem { Name = "小雨粥-"           , Url = "https://live.bilibili.com/1937003510", IsSubscribed = false },
            new LinkItem { Name = "小狮子llllll"      , Url = "https://live.bilibili.com/1713823098", IsSubscribed = false },
            new LinkItem { Name = "辣椒素素素"        , Url = "https://live.bilibili.com/31259021"  , IsSubscribed = false },
            new LinkItem { Name = "今宵一赏三日月"    , Url = "https://live.bilibili.com/1964697875", IsSubscribed = false },
            new LinkItem { Name = "艾诺宝_"           , Url = "https://live.bilibili.com/32593556"  , IsSubscribed = false },
            new LinkItem { Name = "圆宝9号周年版"     , Url = "https://live.bilibili.com/1729382996", IsSubscribed = false },
            new LinkItem { Name = "小鹿小鹿包-"       , Url = "https://live.bilibili.com/1710484900", IsSubscribed = false },
            new LinkItem { Name = "无敌小可ovo"       , Url = "https://live.bilibili.com/1883629712", IsSubscribed = false },
            new LinkItem { Name = "笙笙呼呼呼"        , Url = "https://live.bilibili.com/1912365027", IsSubscribed = false },
            new LinkItem { Name = "酥酥梅の酥"        , Url = "https://live.bilibili.com/1713427443", IsSubscribed = false },
            new LinkItem { Name = "睡不醒的小小小筱大人", Url = "https://live.bilibili.com/1549629"   , IsSubscribed = false },
            new LinkItem { Name = "吃不下了吖"        , Url = "https://live.bilibili.com/1992694372", IsSubscribed = false },
            new LinkItem { Name = "九十九只羊23号生日", Url = "https://live.bilibili.com/25140954"  , IsSubscribed = false },
            new LinkItem { Name = "有点晕的呆呆酱"    , Url = "https://live.bilibili.com/32387899"  , IsSubscribed = false },
            new LinkItem { Name = "阿饼Bing丶"        , Url = "https://live.bilibili.com/31372993"  , IsSubscribed = false },
            new LinkItem { Name = "鱼鱼一只"          , Url = "https://live.bilibili.com/31878555"  , IsSubscribed = false },
            new LinkItem { Name = "沐沐沐阿沐"        , Url = "https://live.bilibili.com/10980241"  , IsSubscribed = false },
            new LinkItem { Name = "闪电小喵0v0"       , Url = "https://live.bilibili.com/32234095"  , IsSubscribed = false },
            new LinkItem { Name = "安可Lufin"         , Url = "https://live.bilibili.com/1783358904", IsSubscribed = false },
            new LinkItem { Name = "羊羊出击-"         , Url = "https://live.bilibili.com/1964567501", IsSubscribed = false },
            new LinkItem { Name = "io六六酱"          , Url = "https://live.bilibili.com/30721522"  , IsSubscribed = false },
            new LinkItem { Name = "困困蛋挞zzz"       , Url = "https://live.bilibili.com/1867582024", IsSubscribed = false },
            new LinkItem { Name = "珂珂超凶-"         , Url = "https://live.bilibili.com/1985025266", IsSubscribed = false },
            new LinkItem { Name = "小蝉不貂-1月9号满月", Url = "https://live.bilibili.com/1919952226", IsSubscribed = false },
            new LinkItem { Name = "兔叽叽master"      , Url = "https://live.bilibili.com/1817612645", IsSubscribed = false },
            new LinkItem { Name = "清水在哪呢"        , Url = "https://live.bilibili.com/1746707849", IsSubscribed = false },
            new LinkItem { Name = "一个懂"            , Url = "https://live.bilibili.com/1866754932", IsSubscribed = false },
            new LinkItem { Name = "冰柠七七"          , Url = "https://live.bilibili.com/1859175097", IsSubscribed = false },
            new LinkItem { Name = "久九九-"           , Url = "https://live.bilibili.com/1922215699", IsSubscribed = false },
            new LinkItem { Name = "璐璐有理"          , Url = "https://live.bilibili.com/1913411682", IsSubscribed = false },
            new LinkItem { Name = "皮皮困困嘟-杂十五冠", Url = "https://live.bilibili.com/1708412391", IsSubscribed = false },
            new LinkItem { Name = "小白菜哈i"         , Url = "https://live.bilibili.com/1949989746", IsSubscribed = false },
            new LinkItem { Name = "金条很乖"          , Url = "https://live.bilibili.com/1750977320", IsSubscribed = false },
            new LinkItem { Name = "小瓶星冰乐"        , Url = "https://live.bilibili.com/32040138"  , IsSubscribed = false },
            new LinkItem { Name = "小墩老师quq"       , Url = "https://live.bilibili.com/1735941537", IsSubscribed = false },
            new LinkItem { Name = "崽崽敲你哇"        , Url = "https://live.bilibili.com/1917433123", IsSubscribed = false },
            new LinkItem { Name = "莓泥不行de"        , Url = "https://live.bilibili.com/1989941730", IsSubscribed = false },
            new LinkItem { Name = "软软-沉淀版"       , Url = "https://live.bilibili.com/1777403816", IsSubscribed = false },
            new LinkItem { Name = "颂颂颂颂大王"      , Url = "https://live.bilibili.com/1792362746", IsSubscribed = false },
            new LinkItem { Name = "是芝士薯片"        , Url = "https://live.bilibili.com/1883623867", IsSubscribed = false },
            new LinkItem { Name = "Ccc_橙"            , Url = "https://live.bilibili.com/1882503571", IsSubscribed = false },
            new LinkItem { Name = "京京-1月14生日版"  , Url = "https://live.bilibili.com/1862081618", IsSubscribed = false },
            new LinkItem { Name = "小烤鱼deity"       , Url = "https://live.bilibili.com/1790622536", IsSubscribed = false },
            new LinkItem { Name = "露露小甜心S"       , Url = "https://live.bilibili.com/1931434921", IsSubscribed = false },
            new LinkItem { Name = "小橙睡饱饱"        , Url = "https://live.bilibili.com/1980664024", IsSubscribed = false },
            new LinkItem { Name = "o小薯芋o"          , Url = "https://live.bilibili.com/1963473606", IsSubscribed = false },
            new LinkItem { Name = "B嫩咪"             , Url = "https://live.bilibili.com/30661283"  , IsSubscribed = false },
            new LinkItem { Name = "铃芽不俐齿"        , Url = "https://live.bilibili.com/30468649"  , IsSubscribed = false },
            new LinkItem { Name = "奶贝点心"          , Url = "https://live.bilibili.com/24329429"  , IsSubscribed = false },
            new LinkItem { Name = "温不温得否"        , Url = "https://live.bilibili.com/1848767744", IsSubscribed = false },
            new LinkItem { Name = "梨佑liyeo"         , Url = "https://live.bilibili.com/1730460383", IsSubscribed = false },
            new LinkItem { Name = "v芽依紫v"          , Url = "https://live.bilibili.com/1837226573", IsSubscribed = false },
            new LinkItem { Name = "小熊软糖给谁了"    , Url = "https://live.bilibili.com/1975553564", IsSubscribed = false },
            new LinkItem { Name = "宁宁不饱饿"        , Url = "https://live.bilibili.com/1856399611", IsSubscribed = false },
            new LinkItem { Name = "想摸小猫"          , Url = "https://live.bilibili.com/1786413272", IsSubscribed = false },
            new LinkItem { Name = "糯糯黛米_17号一周年", Url = "https://live.bilibili.com/1738565515", IsSubscribed = false },
            new LinkItem { Name = "野生蛋糕宝宝闭关中", Url = "https://live.bilibili.com/1732059356", IsSubscribed = false },
            new LinkItem { Name = "美少女饺子"        , Url = "https://live.bilibili.com/1803525155", IsSubscribed = false },
            new LinkItem { Name = "-死在东京轨道上-"  , Url = "https://live.bilibili.com/1728862135", IsSubscribed = false },
            new LinkItem { Name = "笨蛋小喵也"        , Url = "https://live.bilibili.com/1817617414", IsSubscribed = false },
            new LinkItem { Name = "芊妤妤妤鱼"        , Url = "https://live.bilibili.com/1783357303", IsSubscribed = false },
            new LinkItem { Name = "堡堡-18号双满"     , Url = "https://live.bilibili.com/1792592126", IsSubscribed = false },
            new LinkItem { Name = "清纯小伊"          , Url = "https://live.bilibili.com/1713547203", IsSubscribed = false },
            new LinkItem { Name = "小帆团子-"         , Url = "https://live.bilibili.com/1772928082", IsSubscribed = false },
            new LinkItem { Name = "冰冰元气满满"      , Url = "https://live.bilibili.com/1790623615", IsSubscribed = false },
            new LinkItem { Name = "鱼糯糯eiei"        , Url = "https://live.bilibili.com/1950855909", IsSubscribed = false },
            new LinkItem { Name = "小虾米-好运版"     , Url = "https://live.bilibili.com/1901322606", IsSubscribed = false },
            new LinkItem { Name = "呆呆不呆nn"        , Url = "https://live.bilibili.com/1779356547", IsSubscribed = false },
            new LinkItem { Name = "琯琯是谁"          , Url = "https://live.bilibili.com/1917335030", IsSubscribed = false },
            new LinkItem { Name = "u伤碎碎冰"         , Url = "https://live.bilibili.com/1844043899", IsSubscribed = false },
            new LinkItem { Name = "清柚味荔枝"        , Url = "https://live.bilibili.com/1921301482", IsSubscribed = false },
            new LinkItem { Name = "kk-碎碎念念"       , Url = "https://live.bilibili.com/1919953498", IsSubscribed = false },
            new LinkItem { Name = "悲伤草莓挞"        , Url = "https://live.bilibili.com/1817659612", IsSubscribed = false },
            new LinkItem { Name = "世界上没有坏小星"  , Url = "https://live.bilibili.com/1786415034", IsSubscribed = false },
            new LinkItem { Name = "小本子日记屋"      , Url = "https://live.bilibili.com/31837989"  , IsSubscribed = false },
            new LinkItem { Name = "七七七七月-减肥版" , Url = "https://live.bilibili.com/25393098"  , IsSubscribed = false },
            new LinkItem { Name = "霞霞呆"            , Url = "https://live.bilibili.com/1929359592", IsSubscribed = false },
            new LinkItem { Name = "荔枝枝iuk"         , Url = "https://live.bilibili.com/1728869637", IsSubscribed = false }
            //可以继续添加更多默认链接（476）
        };
    }

    // 输出结果手动替换👆DefaultList
    public static void DebugSort(List<LinkItem> subsList)
    {
        // 按 IsSubscribed 降序排序（true在前）
        var sortedList = subsList.OrderByDescending(item => item.IsSubscribed).ToList();
        int totalCount = sortedList.Count;

        // 保底备份：打印成完美对齐的 C# 代码
        Console.WriteLine("new List<LinkItem> {");

        bool hasSubscribedComment = false;
        bool hasUnsubscribedComment = false;

        for (int i = 0; i < totalCount; i++)
        {
            var item = sortedList[i];
            bool isSubscribed = item.IsSubscribed;

            // 分组注释
            if (isSubscribed && !hasSubscribedComment)
            {
                Console.WriteLine("    // 订阅的");
                hasSubscribedComment = true;
            }
            else if (!isSubscribed && !hasUnsubscribedComment)
            {
                Console.WriteLine("    // 不订阅的");
                hasUnsubscribedComment = true;
            }

            // 计算 Name 视觉宽度（中文算2，ASCII算1）
            int nameVisualWidth = item.Name.Sum(c => char.IsAscii(c) || char.IsSymbol(c) ? 1 : 2);
            int namePadding = Math.Max(0, 18 - nameVisualWidth);

            // 计算 Url 视觉宽度（这里所有Url均为ASCII，所以 len 即可）
            int urlVisualWidth = item.Url.Length;  // 纯ASCII，字符数=视觉宽度
            int urlPadding = Math.Max(0, 36 - urlVisualWidth);

            // 构建各部分
            string namePart = $"Name = \"{EscapeString(item.Name)}\"{new string(' ', namePadding)}";
            string urlPart = $"Url = \"{EscapeString(item.Url)}\"{new string(' ', urlPadding)}";
            string subPart = $"IsSubscribed = {isSubscribed.ToString().ToLower()}";
            string durationPart = item.Duration != 2 ? $", Duration = {item.Duration}" : "";

            // 最终 inner：Name(补齐18), Url(补齐36), IsSubscribed...
            string inner = $"{namePart}, {urlPart}, {subPart}{durationPart}";

            string line = $"    new LinkItem {{ {inner} }}";
            if (i < totalCount - 1) line += ",";

            Console.WriteLine(line);
        }

        // 末尾注释
        Console.WriteLine($"    //可以继续添加更多默认链接（{totalCount}）");
        Console.WriteLine("};");
    }

    // 辅助方法：转义字符串中的双引号
    static string EscapeString(string s) => s.Replace("\"", "\\\"");
}